[package]
name = "tupdb"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.38.0", features = ["bundled"] }
tupdb-sql-macro = { path = "../tupdb-sql-macro" }
log = "0.4.29"
sha2 = "0.10.8"
r2d2_sqlite = { version = "0.32.0" }
r2d2 = "0.8.10"

